# Generated by Django 3.0.6 on 2020-05-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='my_user',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
